function singleFig(X1, Y1)
%CREATEFIGURE1(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 15-Dec-2016 02:41:15

% Create figure
figure1 = figure('PaperSize',[20.98404194812 29.67743169791]);

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on','FontSize',12);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'LineWidth',2,'Color',[0 0 1]);

% Create xlabel
xlabel('Bandwidth [Hz]','Interpreter','latex','FontSize',14);

% Create ylabel
ylabel('S [dBm]','Interpreter','latex','FontSize',14);

% Create title
title('Received power with bandwith variation','Interpreter','latex',...
    'FontSize',16);
legend1 = legend('S vs. B','show');
set(legend1,'Location','Best');

